# Generated by Django 5.2.7 on 2025-11-13 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_confirmed",
        ),
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="city",
            field=models.CharField(default="Mumbai", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="description",
            field=models.TextField(default="Dhule"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="address",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Double", "Double"),
                    ("Deluxe", "Deluxe"),
                    ("Suite", "Suite"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
