# Generated by Django 5.2.7 on 2025-11-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_remove_booking_is_confirmed_booking_guests_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hotels/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
