# Generated by Django 5.2.7 on 2025-11-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_roomimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="image",
            new_name="image1",
        ),
        migrations.AddField(
            model_name="room",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.DeleteModel(
            name="RoomImage",
        ),
    ]
