# Generated by Django 5.2.7 on 2025-11-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_roomimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="image1",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="room",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="room",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="room",
            name="image4",
        ),
        migrations.DeleteModel(
            name="RoomImage",
        ),
    ]
