# Generated by Django 5.2.11 on 2026-04-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_rename_image1_room_image_remove_room_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
