# Generated by Django 5.2.11 on 2026-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
